@startuml
skinparam state {
  BackgroundColor LightYellow
  BorderColor Black
}

[*] --> NotReady : [ifstatus!=up_and_configured or service-status==down]
[*] --> Ready : [ifstatus==up_and_configured and service-status==up]

state NotReady
NotReady --> Ready : if-status-changed() or service-status-changed() [ifstatus==up_and_configured and service-status==up]

Ready --> NotReady : if-status-changed [ifstatus!=up_and_configured] / clearAllTimers()
Ready --> NotReady : service-status==down /clearAllTimers() \n send(StopOfferService)

state Ready {
  [*] --> InitialWaitPhase

  state InitialWaitPhase {
    [*] --> TimerSet: SetTimerInRange(INITIAL_DELAY_MIN,INITIAL_DELAY_MAX)
    TimerSet --> RepetitionPhase : Timer expired /send(OfferService)
  }

  state RepetitionPhase {
    [*] --> TimerSet :  [REPETITIONS_MAX>0] /run=0 \n setTimer((2^run)*REPETITIONS_BASE_DELAY)
    TimerSet --> TimerSet : receive(FindService) / waitAndSend(OfferService) \n resetTimer()
    TimerSet --> TimerSet : Timer expired [run<REPETITIONS_MAX] / send(OfferService) \n run++ \n setTimer((2^run)*REPETITIONS_BASE_DELAY)
    TimerSet --> MainPhase : Timer expired [run==REPETITIONS_MAX]
    [*] --> MainPhase : [REPETITIONS_MAX==0]
  }

  state MainPhase {
    [*] --> TimerSet : /setTimer(CYCLIC_ANNOUNCE_DELAY) \n send(OfferService)
    TimerSet --> TimerSet : Timer expired / setTimer(CYCLIC_ANNOUNCE_DELAY) \n send(OfferService)
    TimerSet --> TimerSet : receive(FindService) / waitAndSend(OfferService) \n resetTimer()
  }
}

@enduml
